# Run repoman on travis
# https://github.com/mrueg/repoman-travis
#
language: python
python: 
    - "3.3"
env: 
    - PORTAGE_VER="2.2.10"
before_script:
    - mkdir travis-overlay
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget "http://distfiles.gentoo.org/distfiles/portage-${PORTAGE_VER}.tar.bz2"
    - wget "http://distfiles.gentoo.org/snapshots/portage-latest.tar.xz"
    - sudo chmod 777 /etc/passwd /etc/group /etc /usr
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage/ /usr/portage/distfiles
    - tar xjf portage-${PORTAGE_VER}.tar.bz2
    - tar xJf portage-latest.tar.xz -C /usr/
    - cp portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/
    - rsync --recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --checksum --quiet rsync://rsync.gentoo.org/gentoo-portage /usr/portage
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - wget "http://www.gentoo.org/dtd/metadata.dtd" -O /usr/portage/distfiles/metadata.dtd
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh"
    - chmod 555 spinner.sh
    - cd travis-overlay
script: 
    - ./../spinner.sh "./../portage-${PORTAGE_VER}/bin/repoman full -d"
